#!/bin/sh

# Copyright (c) 2004 Sendmail, Inc. and its suppliers.
#	All rights reserved.
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the sendmail distribution.
#
#
#	$Id: Build,v 1.2 2004/08/31 00:34:32 msk Exp $

exec make OPTIONS="$*"
